### ISSUE TITLE
Milestone 1 tasks

### ISSUE THREAD

**Issue by danielon-5** [UBC-MDS/aridanalysis_py#1]
https://pages.github.ubc.ca/MDS-2020-21/DSCI_524_collab-sw-dev_students/materials/assignments/milestone1.html

**Submission**  
- [x] Create new release named v0.1.0
- [x] Canvas submission (including repo url of public repo, url of release and url of team contract)

**Checklist**
- [x] 1. Team work contract: https://docs.google.com/document/d/1Mj09ipWSXNT89dr6_NltGJKo0Yzihm4130N_78ANriE/edit#
- [x] 2. Pick a topic
- [x] 3. Create project structure for Python:
     - [x] project structure
     - [x] name related to package
     - [x] MIT license
     - [x] update CONTRIBUTORS.md (should be moved to README)
     - [x] edit CONDUCT.md
     - [x] agree and edit CONTRIBUTING.md
     - [x] build README.md containing:
          - [x] summary paragraph
          - [x] bulleted list of functions
          - [x] package fitting in Python ecosystem
- [x] 4. Function specifications:
     - [x] Neel Function
     - [x] Craig Function
     - [x] Daniel Function
     - [x] Santiago Function
- [x] 5. Manage issues
