### ISSUE TITLE
Milestone 2 Tasks

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/aridanalysis_py#42]
https://pages.github.ubc.ca/MDS-2020-21/DSCI_524_collab-sw-dev_students/materials/assignments/milestone2.html

**Submission**  
- [x] Create new Python release named v0.2.0
- [ ] Create new R release named v0.1.0
- [ ] Canvas submission (including repo url of public repo for R repo and Python Repo, url of release for R and Python)

**Checklist**
- [x] 1. Write test cases and code iteratively
    - [x] `arid_eda` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function
        - [x] Handles exceptions with suitable error messages
    - [x] `arid_linreg` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function
        - [x] Handles exceptions with suitable error messages
    - [x] `arid_logreg` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function 
        - [x] Handles exceptions with suitable error messages
    - [x] `arid_countreg` function
        - [x] Revise function
        - [x] Write test function
        - [x] Write function 
        - [x] Handles exceptions with suitable error messages
- [x] 2. Make sure all functions pass `pytest` package
- [x] 3. Exception handling
     - [x] Erroneous Inputs are handled for all functions
     - [x] Exceptions are tested and provide useful messages
- [x] 4. Verify package functions can be installed and used
- [x] 5. Create project structure for R repo
     - [x] R project structure
     - [x] name related to package
     - [x] MIT license
     - [x] DESCRIPTION file.
     - [x] CONTRIBUTING.md
     - [x] usethis::use_code_of_conduct
     - [x] copy README.md containing:
          - [x] summary paragraph
          - [x] bulleted list of functions
          - [x] package fitting in R ecosystem
- [x] 6. R Function specifications
     - [x] Neel Function
     - [x] Craig Function
     - [x] Daniel Function
     - [x] Santiago Function
- [x] 7. R Project GitHub Mechanics
    - [x] Always add meaningful commit messages
    - [x] Use GitHub Flow workflow
    - [x] Manage GitHub issues for communication
        - [x] Copy this task list or a subset over to R project
    - [x] Verify use of proper grammar and full sentences throughout project.
